In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
result=pd.Series([10,20,30,40,50,40])
print(result)

0    10
1    20
2    30
3    40
4    50
5    40
dtype: int64

In [ ]:
car_name=pd.Series(["sierra","Thar","Defender","Scorpio","Pajero","Ertiga","Swift dzire","Audi","BMW"])
print(car_name)

0         sierra
1           Thar
2       Defender
3        Scorpio
4         Pajero
5         Ertiga
6    Swift dzire
7           Audi
8            BMW
dtype: object

In [ ]:
car_name=pd.Series(["sierra","Thar","Defender","Scorpio","Pajero","Ertiga","Swift dzire","Audi","BMW"],index=["TATA","MAHEN","LAND ROV","MAHEN","MIST MOT","MARUTI","MSUZUKI","AUDIAG","BAVMOT"])
print(car_name)

TATA             sierra
MAHEN              Thar
LAND ROV       Defender
MAHEN           Scorpio
MIST MOT         Pajero
MARUTI           Ertiga
MSUZUKI     Swift dzire
AUDIAG             Audi
BAVMOT              BMW
dtype: object

In [ ]:
car_name=pd.Series(["sierra","Thar","Defender","Scorpio","Pajero","Ertiga","Swift dzire","Audi","BMW"],index=["TATA","MAHEN","LAND ROV","MAHEN","MIST MOT","MARUTI","MSUZUKI","AUDIAG","BAVMOT"],dtype=str)
print(car_name)

TATA             sierra
MAHEN              Thar
LAND ROV       Defender
MAHEN           Scorpio
MIST MOT         Pajero
MARUTI           Ertiga
MSUZUKI     Swift dzire
AUDIAG             Audi
BAVMOT              BMW
dtype: object

In [ ]:
name=pd.Series({1:"Iphone",2:"Samsung",3:"Vivo",4:"Nothing",5:"Oneplus",6:"Realme",7:"Moto"})
print(name)

1     Iphone
2    Samsung
3       Vivo
4    Nothing
5    Oneplus
6     Realme
7       Moto
dtype: object

In [ ]:
import pandas as pd
import numpy as np
x=pd.DataFrame({'name':["car","bike","truck"],'model':np.random.randint(2015,2026,size=3)})
print(x)

    name  model
0    car   2018
1   bike   2021
2  truck   2024

In [ ]:
import pandas as pd
import numpy as np
x=pd.DataFrame({'name':["car","bike","truck"],'model':np.random.randint(2015,2026,size=3)})
print(x)

    name  model
0    car   2018
1   bike   2017
2  truck   2022

In [ ]:
a=(["siri","sri","bunny"],[20,21,18],[121,212,221])
print(pd.DataFrame(a,columns=["p1","p2","p3"],index=["Names","Age","Roll.no"]))

           p1   p2     p3
Names    siri  sri  bunny
Age        20   21     18
Roll.no   121  212    221

In [ ]:
a=[{"cricket":1106,"Hockey":312,"kabaddi":627},{"Tennis":222,"volley":528}]
print(pd.DataFrame(a,index=["g1","g2"]))

    cricket  Hockey  kabaddi  Tennis  volley
g1   1106.0   312.0    627.0     NaN     NaN
g2      NaN     NaN      NaN   222.0   528.0

In [ ]:
s=pd.DataFrame(a)
print(s["cricket"])

0    1106.0
1       NaN
Name: cricket, dtype: float64

In [ ]:
car_name=(["sierra","Thar","Defender","Scorpio","Pajero","Ertiga","Swift dzire","Audi","BMW"])
print(pd.DataFrame(car_name,columns=["model"],index=["TATA","MAHEN","LAND ROV","MAHEN","MIST MOT","MARUTI","MSUZUKI","AUDIAG","BAVMOT"]))

                model
TATA           sierra
MAHEN            Thar
LAND ROV     Defender
MAHEN         Scorpio
MIST MOT       Pajero
MARUTI         Ertiga
MSUZUKI   Swift dzire
AUDIAG           Audi
BAVMOT            BMW

In [ ]:
ss=([1,2,3],[1,2,3],[1,2,3,])
ps=pd.DataFrame(ss,columns=['n1','n2','n3'],index=['r1','r2','r3'])
print(ps['n1'])

r1    1
r2    1
r3    1
Name: n1, dtype: int64

In [ ]:
ps['n1']=ps['n2']+ps['n3']
print(ps)

    n1  n2  n3
r1   5   2   3
r2   5   2   3
r3   5   2   3

In [ ]:
ss=([1,2,3],[1,2,3],[1,2,3])
ps=pd.DataFrame(ss,columns=['n1','n2','n3'],index=['r1','r2','r3'])
print(ps.pop('n1'))
print(ps)

r1    1
r2    1
r3    1
Name: n1, dtype: int64
    n2  n3
r1   2   3
r2   2   3
r3   2   3

In [ ]:
import pandas as pd
df=({"Name":['i20','thar','baleno','ertiga'],"model":[2018,2025,2020,2022]})
s=pd.DataFrame(df)
print(s)

     Name  model
0     i20   2018
1    thar   2025
2  baleno   2020
3  ertiga   2022

In [ ]:
s.insert(1,"mileage",[32,12,20,45])
print(s)

     Name  mileage  model
0     i20       32   2018
1    thar       12   2025
2  baleno       20   2020
3  ertiga       45   2022

In [ ]:
a={"diesel":'yes'}
p=s._append(a,ignore_index=True)
print(p)

     Name  mileage   model diesel
0     i20     32.0  2018.0    NaN
1    thar     12.0  2025.0    NaN
2  baleno     20.0  2020.0    NaN
3  ertiga     45.0  2022.0    NaN
4     NaN      NaN     NaN    yes

In [ ]:
import pandas as pd
df=({"Name":['i20','thar','baleno','ertiga'],"model":[2018,2025,2020,2022]})
s=pd.DataFrame(df)
print(s.head(2))

   Name  model
0   i20   2018
1  thar   2025

In [ ]:
print(s.tail(1))

     Name  model
3  ertiga   2022

In [ ]:
print(s.describe())

             model
count     4.000000
mean   2021.250000
std       2.986079
min    2018.000000
25%    2019.500000
50%    2021.000000
75%    2022.750000
max    2025.000000

In [ ]:
print(s.info)

<bound method DataFrame.info of      Name  model
0     i20   2018
1    thar   2025
2  baleno   2020
3  ertiga   2022>

In [ ]:
print(s.loc[1])
print(s.loc[2,"model"])

Name     thar
model    2025
Name: 1, dtype: object
2020

In [ ]:
print(s.iloc[2,1])
print(s.iloc[3,0])

2020
ertiga

In [ ]:
import pandas as pd
df=({"Name":['i20','thar','baleno','ertiga'],"model":[2018,2025,2020,2022]})
s=pd.DataFrame(df)
print(s.values)

[['i20' 2018]
 ['thar' 2025]
 ['baleno' 2020]
 ['ertiga' 2022]]

In [ ]:
print(s.isnull())

    Name  model
0  False  False
1  False  False
2  False  False
3  False  False

In [ ]:
a={"diesel":'yes'}
p=s._append(a,ignore_index=True)
print(p)

     Name   model diesel
0     i20  2018.0    NaN
1    thar  2025.0    NaN
2  baleno  2020.0    NaN
3  ertiga  2022.0    NaN
4     NaN     NaN    yes

In [ ]:
print(p.dropna())

Empty DataFrame
Columns: [Name, model, diesel]
Index: []

In [ ]:
p['diesel']=p['diesel'].fillna("10ltr")
print(p)

     Name   model diesel
0     i20  2018.0  10ltr
1    thar  2025.0  10ltr
2  baleno  2020.0  10ltr
3  ertiga  2022.0  10ltr
4     NaN     NaN    yes

In [ ]:
df=pd.DataFrame({'Name':['nithin','raji','nithin','nithin','raji'],'salary':[35000,20000,40000,21000,36000],'exp':[6,3,2,4,5]})
print(df)

     Name  salary  exp
0  nithin   35000    6
1    raji   20000    3
2  nithin   40000    2
3  nithin   21000    4
4    raji   36000    5

In [ ]:
df.groupby(['Name']).sum()

        salary  exp
Name
nithin   96000   12
raji     56000    8

In [ ]:
df.T

             0      1       2       3      4
Name    nithin   raji  nithin  nithin   raji
salary   35000  20000   40000   21000  36000
exp          6      3       2       4      5

In [ ]:
import pandas as pd
data={'name':['nithin','mahesh','sanvi','basheer','ramya'],
      'gender':['m','m','f','m','f'],
      'city':['hyd','hyd','nrml','nzb','nzb']}
df=pd.DataFrame(data,columns=['name','gender','city'])
print(df)

      name gender  city
0   nithin      m   hyd
1   mahesh      m   hyd
2    sanvi      f  nrml
3  basheer      m   nzb
4    ramya      f   nzb

In [ ]:
obj1=pd.get_dummies(df['city'],dtype=int)
print(obj1)
obj2=pd.get_dummies(df['gender'],dtype=int)
print(obj2)

   hyd  nrml  nzb
0    1     0    0
1    1     0    0
2    0     1    0
3    0     0    1
4    0     0    1
   f  m
0  0  1
1  0  1
2  1  0
3  0  1
4  1  0

In [ ]:
import pandas as pd
data1=pd.DataFrame({'Name':['nithin','shiva','raghu','ajay','rama'],'salary':[38000,20800,40000,21900,36000],'exp':[6,3,2,4,5]})
data2=pd.DataFrame({'Name':['navya','roja','ramesh','nithin','sravya'],'salary':[35000,20000,46000,21000,36700],'exp':[6,3,2,4,5]})
print(data1)
print(data2)

     Name  salary  exp
0  nithin   38000    6
1   shiva   20800    3
2   raghu   40000    2
3    ajay   21900    4
4    rama   36000    5
     Name  salary  exp
0   navya   35000    6
1    roja   20000    3
2  ramesh   46000    2
3  nithin   21000    4
4  sravya   36700    5

In [ ]:
df=pd.concat([data1,data2])
print(df)

     Name  salary  exp
0  nithin   38000    6
1   shiva   20800    3
2   raghu   40000    2
3    ajay   21900    4
4    rama   36000    5
0   navya   35000    6
1    roja   20000    3
2  ramesh   46000    2
3  nithin   21000    4
4  sravya   36700    5

In [ ]:
df=pd.concat([data1,data2],ignore_index=True)
print(df)

     Name  salary  exp
0  nithin   38000    6
1   shiva   20800    3
2   raghu   40000    2
3    ajay   21900    4
4    rama   36000    5
5   navya   35000    6
6    roja   20000    3
7  ramesh   46000    2
8  nithin   21000    4
9  sravya   36700    5

In [ ]:
import pandas as pd
data1={'Name':['nithin','shiva','nithin','pushpa','siri'],
       'salary':[38000,20800,40000,21900,36000],
       'exp':[6,3,2,4,5]}
info=pd.DataFrame(data1)
print(d)
print("--"*15)
info=info.drop_duplicates(subset=['Name'])
print(info)

NameError: name 'd' is not defined